<?php
$siteTitle="GRE Word Definitions";

// Must update $homesite before uploading
$homesite="http://saosx.com";
//$homesite="http://localhost/GREWords";
$ucpage="$homesite/und_const.php";
$navigate ="<ul id=\"navigation\">
     <li><a href=\"$homesite/index.php\" id=\"homenav\">Home</a></li>
     <li><a href=\"$homesite/solaris.php\" id=\"solarisnav\">Solaris</a></li>
     <li><a href=\"$homesite/programming.html\" id=\"prognav\">Programming</a></li>
     <li><a href=\"$homesite/other_troubleshooting.php\" id=\"troublenav\">Win+Linux</a></li>
     <li><a href=\"$homesite/mw/\" id=\"oth_worldnav\">My World</a> </li>
     </ul>";

?>
